FROM docker.io/library/golang:1.22 AS builder

WORKDIR /app

COPY go.mod ./

RUN go mod download

COPY . .

RUN go build -o notification-worker .


FROM docker.io/library/debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/notification-worker .

CMD ["./notification-worker"]
